# - run sshd with builder user's public key
#   so that builder can ssh directly in as root
#
FROM centos:5

RUN yum -y install openssh-server
RUN yum -y install python-simplejson
RUN sed -i \
  's/PermitRootLogin without-password/PermitRootLogin yes/' \
  /etc/ssh/sshd_config
RUN sed -i \
  's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' \
  /etc/pam.d/sshd
RUN service sshd start  # to generate host keys
RUN mkdir /root/.ssh
COPY ./tmp/id_dsa.pub /root/.ssh/authorized_keys
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
